### ISSUE TITLE
og:title should not contain site.title

### ISSUE THREAD

**Issue by pathawks** [benbalter/jekyll-seo-tag#10]
From [Facebook](https://developers.facebook.com/docs/sharing/webmasters#markup):

> `og:title`: The title of your article without any branding such as your site name.

**Comment by benbalter** [comment]
Makes sense. @pathawks if you're interested, should be a super simple pull request?

**Comment by pathawks** [comment]
No problem. I’ll take a look later today :+1:

**Comment by XhmikosR** [comment]
Sorry for bumping an old issue but I think the problem I see is related to this change.

I'm getting

```
Attempted Frozen Title Change
It appears that you are trying to change the property og:title from Home · MPC-HC to Home. If so, you are not allowed to for this object because too many actions have been published against it.
```

I'm using the plugin as `{% seo title=false %}`.

**Comment by pathawks** [comment]
@XhmikosR Can you submit a PR with a failing test, or provide some other way for me to recreate this problem?

**Comment by XhmikosR** [comment]
@pathawks: it happens with this branch https://github.com/mpc-hc/mpc-hc.org/compare/jekyll-seo-tag

**Comment by pathawks** [comment]
@XhmikosR Site builds fine for me. If you are still having trouble, please open a new issue.
