### ISSUE TITLE
Author name == Twitter Username?

### ISSUE THREAD

**Issue by pathawks** [benbalter/jekyll-seo-tag#18]
We are currently assuming that, if an `author` is provided for a post, the `author` is [a string that corresponds to a Twitter username.](https://github.com/benbalter/jekyll-seo-tag/blob/v0.1.3/lib/template.html#L92-L94)

That is to say, `author: "Pat Hawks"` would cause false data to be rendered, because my Twitter username has no space in it, but I *do* include a space in the name I include on my site.

Not sure of the best path forward. We could assume `author` is a hash that has keys `twitter` and `name`. We could look up the provided `author` name in a hash in `_data/`, or something...

**Comment by benbalter** [comment]
It adds some complexity, but I'd be fine taking [the approach Jekyll-Feed takes](https://github.com/jekyll/jekyll-feed/blob/98cd38e7220b7e692f7f0f1186228a5673267adf/README.md#optional-configuration-options), meaning, it can either be a string (the user's username) or a hash, with some sort of username property, both falling back to the global config, if none is present.

**Comment by benbalter** [comment]
Fixed by #26 / #52
