### ISSUE TITLE
Consolidate and clean up JSON-LD

### ISSUE THREAD

**Issue by pathawks** [benbalter/jekyll-seo-tag#27]
Right now, we are outputting (potentially) *four* JSON-LD blocks on a single page, each claiming the page to be a different `@type`, any many containing redundant data.

I believe we could consolidate these into a single block with a single `@type` and still convey all the same information.

**Comment by pathawks** [comment]
I am tempted to tackle this by creating a Hash in Ruby with all of the data and passing that to the template, instead of doing everything in Liquid.

I think it would make for cleaner code but, alas, I understand that the more we can do in Liquid the easier the code review is.

**Comment by benbalter** [comment]
> I think it would make for cleaner code but, alas, I understand that the more we can do in Liquid the easier the code review is.

String manipulation is *generally* okay, if it's just a matter of building a hash and running `to_json`, but when you start doing that with user input, things get tricky. What happens if a user sets their site name to 100MB of random text?

**Comment by pathawks** [comment]
Closing this in favor of #28 so I can put my `code` where my mouth is
