### ISSUE TITLE
Fall back to truncated post excerpt if none given.

### ISSUE THREAD

**Issue by benbalter** [benbalter/jekyll-seo-tag#30]

**Comment by pathawks** [comment]
Is that better than just letting the consumer (Facebook or whomever) figure it out on their own?

**Comment by parkr** [comment]
> Is that better than just letting the consumer (Facebook or whomever) figure it out on their own?

I think so. A post `excerpt` will generally know what the content is, whereas Facebook might take the header or something else as the content excerpt. If you have a sidebar, it may use the links on your sidebar. Etc, etc.
