### ISSUE TITLE
Support for global author's data in _data

### ISSUE THREAD

**Issue by benbalter** [benbalter/jekyll-seo-tag#31]
Where the object added in https://github.com/benbalter/jekyll-seo-tag/pull/26, can be replaced with a name, which would pull `site.data.authors[name]`.

**Comment by pathawks** [comment]
**YES PLEASE** :+1:

**Comment by parkr** [comment]
:+1: on this too!

**Comment by pathawks** [comment]
I can take a stab at this over the weekend.

**Comment by ickc** [comment]
:+1:

**Comment by benbalter** [comment]
Fixed by #52
