### ISSUE TITLE
 Use page.excerpt for og:description

### ISSUE THREAD

**Issue by CGarces** [benbalter/jekyll-seo-tag#35]
There is any possibility to use the page.excerpt if page description not is available?
I think that is a better approach that use the site.description.
This is my current code that cam be adapted is some way

```HTML
	<meta property="og:description" content="{% if page.layout != "post" %}{{ site.description | strip_html }}{% else %}{{ page.excerpt | strip_html }}{% endif %}"/>
```

**Comment by CGarces** [comment]
Looks like a similar issue is fixed
https://github.com/benbalter/jekyll-seo-tag/commit/6dab82639ea393f93033efc5e3f5005e864de2b4

Maybe is better limit the content. If page.excerpt not is set jekyll set a default value that maybe is too big.

	{{ page.excerpt | strip_html | truncatewords: 250 }}

How can I know when this fix will be promoted to rubygems?

**Comment by benbalter** [comment]
Fixed by https://github.com/benbalter/jekyll-seo-tag/pull/34, which should be available in the next release.
