### ISSUE TITLE
Suport for BlogPosting

### ISSUE THREAD

**Issue by CGarces** [benbalter/jekyll-seo-tag#37]
The template is defined as NewsArticle, but in some sites BlogPosting is more accurate.

Both types inherit from Article, change the `@type` based on the value at _config.yml should work. 

Something like

```YAML
seo:
  schema: BlogPosting
```

**Comment by CGarces** [comment]
Opps I see the WIP at
https://github.com/benbalter/jekyll-seo-tag/pull/28

**Comment by pathawks** [comment]
Thanks for the interest :+1:

I’ll try to put some polish on that PR when I can.
