### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by boturnbow** [benbalter/jekyll-seo-tag#42]
I was starting to make a pull request for #24, but after forking and cloning `master` all tests fail with:

```
NoMethodError:
       private method `new' called for Jekyll::SeoTag:Class
```

I tried several things (ruby versions, gem re-installs) and then tested the 0.1.4 tag with the same test failures. Just to be sure I pushed a small readme change to travis and the build failed on travis, too: https://travis-ci.org/boturnbow/jekyll-seo-tag/builds/106609578. I cloned jekyll/jekyll and benbalter/jekyll-avatar and ran tests locally - all passed. So, that leads me to believe that the problem is not entirely a local-to-my-machine problem.

Any insights?

**Comment by pathawks** [comment]
Yes, this is due to [github/pages-gem](https://github.com/github/pages-gem) updating to Jekyll 3 and, with it, Liquid 3.

This was caused by Shopify/liquid#321

We just need to tweak our tests to use `.parse` instead of `.new`

**Comment by boturnbow** [comment]
Cool beans!
