### ISSUE TITLE
Add "keywords"

### ISSUE THREAD

**Issue by parkr** [benbalter/jekyll-seo-tag#9]
`site.keywords` can be `join`'d by a `,` to yield the `keywords` meta tag.

**Comment by benbalter** [comment]
First two results for "meta tags seo":

* [Reasons Why You Should Stop Using Keywords Meta Tag](http://cohlab.com/blog/stop-using-keywords-meta-tag.html)
* [Official Google Webmaster's blog: Google does not use the keywords meta tag in web ranking](https://googlewebmastercentral.blogspot.com/2009/09/google-does-not-use-keywords-meta-tag.html)

**Comment by parkr** [comment]
I stand corrected, then. :smile:
